name: uc-python
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.11
    - category_encoders>=2.6
    - ipykernel>=6.28
    - matplotlib>=3.8
    - missingno>=0.4
    - mlflow=2.9
    - nbconvert>=7.14
    - numpy>=1.26
    - pandas>=2.1
    - pip>=23.3
    - plotnine>=0.12
    - pytest>=7.4
    - scikit-learn>=1.3
    - seaborn>=0.13
